### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by ghost** [cv-rits/LMSCNet#6]
Hi,

I downloaded the **semanticKITTI_v1.1_dscale.zip** and unzip under the main_folder/kitti. 

When I ran "python LMSCNet/data/labels_downscale.py --dset_root kitti/", it was successful

However, when I ran either:
"python LMSCNet/validate.py --weights checkpoints/LMSCNet.pth --dset_root kitti/" or
"python LMSCNet/test.py --weights checkpoints/LMSCNet.pth --dset_root kitti/"

It shows:
"sequences = list(sorted(glob(os.path.join(self.root_dir, 'dataset', 'sequences', '*')))[i] for i in self.split[self.phase])
IndexError: list index out of range"

Can you  help? thanks!
Tao

**Comment by luigui2906** [comment]
Hi,

Thanks for the interest in our work. If you are using V1.1 of the dataset, then you do not need to run `labels_downscale.py` as it will generate the same data as **semanticKITTI_v1.1_dscale.zip** downloaded from our link.

Regarding the issue, please check the file structure of your project, it should be the same as defined for the kitti dataset, you are having this error because no sequence folder was found at provided path.

Best,
Luis
